In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
# preprocessing/decomposition
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.decomposition import PCA, FastICA, FactorAnalysis, KernelPCA

# keras 
from keras.models import Sequential, load_model
from keras.layers import Dense, Dropout, BatchNormalization, Activation
from keras.wrappers.scikit_learn import KerasRegressor
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras import backend as K
from keras.regularizers import l2
from keras.layers.convolutional import MaxPooling2D, Convolution2D, AveragePooling2D
from keras.layers import Input, Dropout, Dense, Flatten, Activation
from keras.layers.normalization import BatchNormalization
from keras.layers.merge import concatenate
from keras import regularizers
from keras import initializers
from keras.layers.advanced_activations import ThresholdedReLU
from keras.models import Model
from keras.callbacks import ReduceLROnPlateau

# Utils
from keras.utils.layer_utils import convert_all_kernels_in_model
from keras.utils.data_utils import get_file

# model evaluation
from sklearn.model_selection import cross_val_score, KFold, train_test_split
from sklearn.metrics import r2_score, mean_squared_error

# supportive models
from sklearn.ensemble import GradientBoostingRegressor
# feature selection (from supportive model)
from sklearn.feature_selection import SelectFromModel

Using TensorFlow backend.

In [2]:
seed = 6
type = 2
all_dat = pd.read_csv("../data/cleanData.csv")
test_id = pd.read_csv("../data/testID.csv")
all_dat.head()

,ID,X0,X1,X2,X3,X4,X5,X6,X8,X10,...,X2m,X0_A_Only,X0_A_Only_MeanY,X0_A_Only_SDY,X0_A_Only.1,X0_A_Only_MeanY.1,X0_A_Only_SDY.1,dupCnt,IDScale,y
0,0,0.185185,0.777778,0.90,0.000000,1.0,0.606061,0.818182,0.583333,0,...,0,0,0,0,0,0,0,0.0,0.000000,130.81000
1,1,0.944444,0.777778,0.26,0.833333,1.0,0.575758,0.000000,0.916667,0,...,0,1,1,1,1,1,1,0.0,0.000119,71.34112
2,2,0.351852,0.037037,0.68,0.000000,1.0,0.030303,0.545455,1.000000,0,...,0,0,0,0,0,0,0,0.0,0.000238,NaN
3,3,0.944444,0.777778,0.88,0.833333,1.0,0.000000,0.818182,0.375000,0,...,0,1,1,1,1,1,1,0.0,0.000356,NaN
4,4,0.944444,0.407407,0.26,0.833333,1.0,0.757576,1.000000,0.541667,0,...,0,1,1,1,1,1,1,0.0,0.000475,NaN

In [3]:
train = all_dat[-all_dat['y'].isnull()].copy()
test = all_dat[all_dat['y'].isnull()].copy()
test_raw = pd.merge(all_dat, test_id, on = 'ID', how='inner')
test_raw.head()

,ID,X0,X1,X2,X3,X4,X5,X6,X8,X10,...,X2m,X0_A_Only,X0_A_Only_MeanY,X0_A_Only_SDY,X0_A_Only.1,X0_A_Only_MeanY.1,X0_A_Only_SDY.1,dupCnt,IDScale,y
0,1,0.944444,0.777778,0.26,0.833333,1.0,0.575758,0.000000,0.916667,0,...,0,1,1,1,1,1,1,0.0,0.000119,71.34112
1,2,0.351852,0.037037,0.68,0.000000,1.0,0.030303,0.545455,1.000000,0,...,0,0,0,0,0,0,0,0.0,0.000238,NaN
2,3,0.944444,0.777778,0.88,0.833333,1.0,0.000000,0.818182,0.375000,0,...,0,1,1,1,1,1,1,0.0,0.000356,NaN
3,4,0.944444,0.407407,0.26,0.833333,1.0,0.757576,1.000000,0.541667,0,...,0,1,1,1,1,1,1,0.0,0.000475,NaN
4,5,0.407407,0.666667,0.88,0.333333,1.0,0.727273,0.727273,0.500000,0,...,0,0,0,0,0,0,0,0.0,0.000594,NaN

In [4]:
# X, y preparation
X, y = train.drop(['y', 'ID'], axis=1).values, train.y.values
print(X.shape)

(4251, 485)

In [12]:
# check shape
print('\nTrain shape: {}\nTest shape: {}'.format(train.shape, test.shape))

def root_mean_squared_error(y_true, y_pred):
        return K.sqrt(K.mean(K.square(y_pred - y_true), axis=-1)) 
    
def r2_keras(y_true, y_pred):
    SS_res =  K.sum(K.square( y_true - y_pred )) 
    SS_tot = K.sum(K.square( y_true - K.mean(y_true) ) ) 
    return ( 1 - SS_res/(SS_tot + K.epsilon()) )

def createDeepModel(dropout_level = 0.25, activation = 'tanh'):
    model = Sequential()
    model.add(Dense(1024, input_dim=input_dims, kernel_initializer="he_normal"))
    model.add(BatchNormalization())
    model.add(Activation(activation))
    model.add(Dropout(dropout_level))
    
    model.add(Dense(1024, kernel_initializer="he_normal"))
    model.add(BatchNormalization())
    model.add(Activation(activation))
    model.add(Dropout(dropout_level))
    
    model.add(Dense(1024, kernel_initializer="he_normal"))
    model.add(BatchNormalization())
    model.add(Activation(activation))
    model.add(Dropout(dropout_level))
    
    model.add(Dense(1024, kernel_initializer="he_normal"))
    model.add(BatchNormalization())
    model.add(Activation(activation))
    model.add(Dropout(dropout_level))
    
    model.add(Dense(1024, kernel_initializer="he_normal"))
    model.add(BatchNormalization())
    model.add(Activation(activation))
    model.add(Dropout(dropout_level))
    
    model.add(Dense(786, kernel_initializer="he_normal"))
    model.add(BatchNormalization())
    model.add(Activation(activation))
    model.add(Dropout(dropout_level))
    
    model.add(Dense(786, kernel_initializer="he_normal"))
    model.add(BatchNormalization())
    model.add(Activation(activation))
    model.add(Dropout(dropout_level))
    
    model.add(Dense(786, kernel_initializer="he_normal"))
    model.add(BatchNormalization())
    model.add(Activation(activation))
    model.add(Dropout(dropout_level))
    
    model.add(Dense(786, kernel_initializer="he_normal"))
    model.add(BatchNormalization())
    model.add(Activation(activation))
    model.add(Dropout(dropout_level))
    
    model.add(Dense(786, kernel_initializer="he_normal"))
    model.add(BatchNormalization())
    model.add(Activation(activation))
    model.add(Dropout(dropout_level))

    model.add(Dense(786, kernel_initializer="he_normal", kernel_regularizer = l2(1.e-5)))
    model.add(BatchNormalization())
    model.add(Activation(activation))
    model.add(Dropout(dropout_level))
    
    model.add(Dense(1, activation='linear'))
    return model

Train shape: (3401,)
Test shape: (4167, 487)

In [6]:
# initialize input dimension
input_dims = train.shape[1]-2

In [7]:
# X_test preparation
X_test = test_raw.drop(['y', 'ID'], axis=1).values
print(X_test.shape)

(4209, 485)

In [ ]:
# define path to save model
import os
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

numFolds = 5
kf = KFold(n_splits=numFolds)
kfidx = 1

yfull_test = []
yfull_train = []
yfull_target = []

def r2_keras(y_true, y_pred):
    SS_res =  K.sum(K.square( y_true - y_pred )) 
    SS_tot = K.sum(K.square( y_true - K.mean(y_true) ) ) 
    return ( 1 - SS_res/(SS_tot + K.epsilon()) )

# make np.seed fixed
np.random.seed(1989)

for train, valid in kf.split(X):
    # prepare callbacks
    K.clear_session()
    #model = simpleModel_x()
    model = createDeepModel(dropout_level=0.15,activation='relu')
    model.compile(loss= 'mean_squared_error', # one may use 'mean_absolute_error' as alternative
                  optimizer='adadelta',
                  metrics=[r2_keras] # you can add several if needed
                 )
    
    if kfidx == 1:
        print(model.summary())
    
    X_train, X_valid, y_train, y_valid = X[train], X[valid], y[train], y[valid]
    
    kfold_weights_path = os.path.join('', 'kf13_' + str(kfidx) + '.h5')
    print('Computing fold {} out of {}...'.format(kfidx, numFolds))
    callbacks = [
        EarlyStopping(
            monitor='val_loss', 
            patience=35, # was 10
            verbose=1),

        ModelCheckpoint(
            kfold_weights_path, 
            monitor='val_loss', 
            save_best_only=True, 
            verbose=0),

        ReduceLROnPlateau(monitor='val_loss', factor=0.25, patience=15, min_lr=0.00005, verbose=1),
    ]
    
    model.fit(X_train, y_train, epochs = 500, verbose = 0, batch_size=256,
                        validation_data = (X_valid, y_valid), 
                        callbacks = callbacks, shuffle = True)
    
    if os.path.isfile(kfold_weights_path):
        model.load_weights(kfold_weights_path)
        
    # check performance on train set
    print('MSE train: {}'.format(mean_squared_error(y_train, model.predict(X_train))**0.5)) # mse train
    print('R^2 train: {}'.format(r2_score(y_train, model.predict(X_train)))) # R^2 train

    # check performance on validation set
    print('MSE val: {}'.format(mean_squared_error(y_valid, model.predict(X_valid))**0.5)) # mse val
    print('R^2 val: {}'.format(r2_score(y_valid, model.predict(X_valid)))) # R^2 val
    
    # keep track of OOF results
    res_oof = model.predict(X_valid)
    yfull_train.append(res_oof)
    yfull_target.append(y_valid)
    
    # predict results
    res = model.predict(X_test)
    yfull_test.append(res)
    
    # update the counter
    kfidx += 1
    
# then.. overall..
train_full_result = np.array(yfull_train[0])
train_target_full = np.array(yfull_target[0])
for i in range(1, numFolds):
    train_full_result = np.concatenate((train_full_result, yfull_train[i]), axis = 0)
    train_target_full = np.concatenate((train_target_full, yfull_target[i]), axis = 0)
print('OVERALL MSE OOF VAL: {}'.format(mean_squared_error(train_target_full, train_full_result)**0.5)) # mse val
print('OVERALL R^2 OOF VAL: {}'.format(r2_score(train_target_full, train_full_result))) # R^2 val

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_1 (Dense)              (None, 1024)              497664
_________________________________________________________________
batch_normalization_1 (Batch (None, 1024)              4096
_________________________________________________________________
activation_1 (Activation)    (None, 1024)              0
_________________________________________________________________
dropout_1 (Dropout)          (None, 1024)              0
_________________________________________________________________
dense_2 (Dense)              (None, 1024)              1049600
_________________________________________________________________
batch_normalization_2 (Batch (None, 1024)              4096
_________________________________________________________________
activation_2 (Activation)    (None, 1024)              0
_________________________________________________________________
dropout_2 (Dropout)          (None, 1024)              0
_________________________________________________________________
dense_3 (Dense)              (None, 1024)              1049600
_________________________________________________________________
batch_normalization_3 (Batch (None, 1024)              4096
_________________________________________________________________
activation_3 (Activation)    (None, 1024)              0
_________________________________________________________________
dropout_3 (Dropout)          (None, 1024)              0
_________________________________________________________________
dense_4 (Dense)              (None, 1024)              1049600
_________________________________________________________________
batch_normalization_4 (Batch (None, 1024)              4096
_________________________________________________________________
activation_4 (Activation)    (None, 1024)              0
_________________________________________________________________
dropout_4 (Dropout)          (None, 1024)              0
_________________________________________________________________
dense_5 (Dense)              (None, 1024)              1049600
_________________________________________________________________
batch_normalization_5 (Batch (None, 1024)              4096
_________________________________________________________________
activation_5 (Activation)    (None, 1024)              0
_________________________________________________________________
dropout_5 (Dropout)          (None, 1024)              0
_________________________________________________________________
dense_6 (Dense)              (None, 786)               805650
_________________________________________________________________
batch_normalization_6 (Batch (None, 786)               3144
_________________________________________________________________
activation_6 (Activation)    (None, 786)               0
_________________________________________________________________
dropout_6 (Dropout)          (None, 786)               0
_________________________________________________________________
dense_7 (Dense)              (None, 786)               618582
_________________________________________________________________
batch_normalization_7 (Batch (None, 786)               3144
_________________________________________________________________
activation_7 (Activation)    (None, 786)               0
_________________________________________________________________
dropout_7 (Dropout)          (None, 786)               0
_________________________________________________________________
dense_8 (Dense)              (None, 786)               618582
_________________________________________________________________
batch_normalization_8 (Batch (None, 786)               3144
_________________________________________________________________
activation_8 (Activation)    (None, 786)               0
_________________________________________________________________
dropout_8 (Dropout)          (None, 786)               0
_________________________________________________________________
dense_9 (Dense)              (None, 786)               618582
_________________________________________________________________
batch_normalization_9 (Batch (None, 786)               3144
_________________________________________________________________
activation_9 (Activation)    (None, 786)               0
_________________________________________________________________
dropout_9 (Dropout)          (None, 786)               0
_________________________________________________________________
dense_10 (Dense)             (None, 786)               618582
_________________________________________________________________
batch_normalization_10 (Batc (None, 786)               3144
_________________________________________________________________
activation_10 (Activation)   (None, 786)               0
_________________________________________________________________
dropout_10 (Dropout)         (None, 786)               0
_________________________________________________________________
dense_11 (Dense)             (None, 786)               618582
_________________________________________________________________
batch_normalization_11 (Batc (None, 786)               3144
_________________________________________________________________
activation_11 (Activation)   (None, 786)               0
_________________________________________________________________
dropout_11 (Dropout)         (None, 786)               0
_________________________________________________________________
dense_12 (Dense)             (None, 1)                 787
=================================================================
Total params: 8,634,755
Trainable params: 8,615,083
Non-trainable params: 19,672
_________________________________________________________________
None
Computing fold 1 out of 5...

In [ ]:
test_full_result = np.array(yfull_test[0])
for i in range(1, numFolds):
    test_full_result += np.array(yfull_test[i])
test_full_result /= numFolds
# create df and convert it to csv
test_df = {'ID': test_raw['ID'], 'y': test_full_result.ravel()}
test_full_result_df = pd.DataFrame(test_df, columns = ['ID', 'y'])
test_full_result_df.to_csv('ivan_keras_0_5378_test.csv', index=False)

In [50]:
train_df = {'ID': all_dat[-all_dat['y'].isnull()]['ID'], 'y': train_full_result.ravel()}
train_full_result_df = pd.DataFrame(train_df, columns = ['ID', 'y'])

train_full_result_df.to_csv('ivan_keras_0_5378_train.csv',index=False)